### ISSUE TITLE
OpenDTU is shown as Fronius

### ISSUE THREAD

**Issue by sbernhard** [henne49/dbus-opendtu#118]
**Follow the Troubleshooting Section**
Installed the latest dbus-opendtu with last commit Sep 17. Fronius PV is used, too

**Describe the Problem**
Additionally to the Fronius PV inverter, the OpenDTU is shown but with Fronius logo on it.

CerboGX Version 3.01

**Expected behavior**
The Fronius logo should not be shown on the OpenDTU PV inverter

**Screenshots**
![image](https://github.com/henne49/dbus-opendtu/assets/25485845/abd1a9e5-06c0-4307-baaa-13aeccd90e91)

Additional question, should the line from the OpenDTU PV inverter really shown as in the screenshot? I would expect that the line is similar to the Fronius PV Inverter because the OpenDTU is not only used to load the battery but also to provide power to AC loads etc.

**Comment by 0x7878** [comment]
First of all, thank you @sbernhard for letting us know. From our side, it is not intended. Since Victron changed their firmware upon version 3+ the view is very different from before. What does it look like in VRM? 

It is funny that you have this behavior.  We tried the other way around to emulate a Fronius inverter but without success. 

Even though it's not the expected answer I hope this is better than nothing.
